### ISSUE TITLE
点击一些菜单会报这个错，查了很久也没有查到问题(TT)

### ISSUE THREAD

**Issue by AIOUWAJIE** [Yiuman/citrus-vuetify#13]
![mmexport1683770155011.png](https://github.com/Yiuman/citrus-vuetify/assets/101471000/0f93a508-6d12-4713-a7ec-1007aecc1522)

![mmexport1683770157109.png](https://github.com/Yiuman/citrus-vuetify/assets/101471000/434cdff0-83fe-4382-820c-c5c54c3e654d)

**Comment by AIOUWAJIE** [comment]
![mmexport1683771024595.png](https://github.com/Yiuman/citrus-vuetify/assets/101471000/dae4b7a6-6e7c-49f2-9c35-410baae6c13c)

**Comment by Yiuman** [comment]
com.github.yiuman.citrus.security.authorize.AuthorizeAdvice#hasPermission提示没权限
1.debug 看下为啥
2. 是否是data_init.sql中的初始化脚本未完全执行
3. 是否已经使用了admin账号或者自建账号是否给了权限与数据范围

**Comment by AIOUWAJIE** [comment]
我确认sql语句全部执行成功了，但我注意到有些表内容是空的仍然是那个问题![mmexport1683770155011.png](https://github.com/Yiuman/citrus-vuetify/assets/101471000/6e54dd67-338c-430e-91cc-c0a5be72cdd3)

**Comment by Yiuman** [comment]
debug在com.github.yiuman.citrus.system.hook.HasLoginHook跟踪下吧
看到无权限的上一行是token无效了  看下是否已经传了
